<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\RecordStatus;
use App\Models\Department;
use App\Models\Plant;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * Demo accounts, one per role. Passwords come from MDP_DEMO_PASSWORD so a
 * deployment can seed without shipping a known credential.
 */
class UserSeeder extends Seeder
{
    /**
     * @var array<int, array{name: string, email: string, role: string, department: string, position: string}>
     */
    private const USERS = [
        ['name' => 'Super Administrator', 'email' => 'superadmin@yusufazharzaini.test', 'role' => 'SUPER_ADMIN', 'department' => 'MGT', 'position' => 'System Owner'],
        ['name' => 'Application Admin', 'email' => 'admin@yusufazharzaini.test', 'role' => 'ADMIN', 'department' => 'MGT', 'position' => 'IT Administrator'],
        ['name' => 'Purchasing Staff', 'email' => 'purchasing@yusufazharzaini.test', 'role' => 'PURCHASING', 'department' => 'PUR', 'position' => 'Purchasing Officer'],
        ['name' => 'Warehouse Staff', 'email' => 'warehouse@yusufazharzaini.test', 'role' => 'WAREHOUSE', 'department' => 'WHS', 'position' => 'Warehouse Officer'],
        ['name' => 'Logistic Staff', 'email' => 'logistic@yusufazharzaini.test', 'role' => 'LOGISTIC', 'department' => 'LOG', 'position' => 'Logistic Officer'],
        ['name' => 'Plant Manager', 'email' => 'management@yusufazharzaini.test', 'role' => 'MANAGEMENT', 'department' => 'MGT', 'position' => 'Plant Manager'],
        ['name' => 'Read Only User', 'email' => 'viewer@yusufazharzaini.test', 'role' => 'VIEWER', 'department' => 'PRD', 'position' => 'Production Planner'],
    ];

    public function run(): void
    {
        $password = Hash::make((string) env('MDP_DEMO_PASSWORD', 'password123'));
        $departments = Department::query()->pluck('id', 'code');
        $plantId = Plant::query()->orderBy('id')->value('id');

        foreach (self::USERS as $index => $definition) {
            $user = User::query()->withTrashed()->updateOrCreate(
                ['email' => $definition['email']],
                [
                    // ulid is generated by the HasUlid trait, not mass assigned.
                    'name' => $definition['name'],
                    'password' => $password,
                    'email_verified_at' => now(),
                    'department_id' => $departments[$definition['department']] ?? null,
                    'plant_id' => $plantId,
                    'employee_code' => sprintf('EMP-%04d', $index + 1),
                    'position' => $definition['position'],
                    'phone' => '0812'.str_pad((string) (10000 + $index), 8, '0', STR_PAD_LEFT),
                    'status' => RecordStatus::ACTIVE,
                ],
            );

            $user->syncRoles([$definition['role']]);
        }
    }
}
