<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\RecordStatus;
use App\Models\Concerns\HasRecordStatus;
use App\Models\Concerns\HasSearch;
use App\Models\Concerns\HasUlid;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Plant extends Model
{
    use HasFactory;
    use HasRecordStatus;
    use HasSearch;
    use HasUlid;
    use SoftDeletes;

    /**
     * `ulid` is absent: it is generated by HasUlid, never supplied.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code', 'name', 'address', 'city', 'pic_name', 'pic_phone', 'status',
    ];

    /**
     * @var array<int, string>
     */
    protected array $searchable = ['code', 'name', 'city'];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return ['status' => RecordStatus::class];
    }

    /**
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeWithListRelations(Builder $query): Builder
    {
        return $query->withCount(['warehouses', 'users']);
    }

    public function warehouses(): HasMany
    {
        return $this->hasMany(Warehouse::class);
    }

    public function purchaseOrders(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class);
    }

    public function deliveries(): HasMany
    {
        return $this->hasMany(Delivery::class);
    }

    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }
}
