<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\RecordStatus;
use App\Models\Concerns\HasRecordStatus;
use App\Models\Concerns\HasSearch;
use App\Models\Concerns\HasUlid;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory;
    use HasRecordStatus;
    use HasRoles;
    use HasSearch;
    use HasUlid;
    use Notifiable;
    use SoftDeletes;

    /**
     * `ulid` is absent: it is generated by HasUlid, never supplied. Roles are
     * assigned through spatie's syncRoles(), never mass assigned.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'department_id',
        'plant_id',
        'employee_code',
        'position',
        'phone',
        'locale',
        'status',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * @var array<int, string>
     */
    protected array $searchable = ['name', 'email', 'employee_code', 'position'];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'status' => RecordStatus::class,
        ];
    }

    /**
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeWithListRelations(Builder $query): Builder
    {
        return $query->with([
            'department:id,code,name',
            'plant:id,ulid,code,name',
            'roles:id,name',
        ]);
    }

    /**
     * Users attached to one plant, used to scope notifications and reports.
     *
     * @param  Builder<static>  $query
     * @return Builder<static>
     */
    public function scopeAtPlant(Builder $query, int $plantId): Builder
    {
        return $query->where('plant_id', $plantId);
    }

    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    public function plant(): BelongsTo
    {
        return $this->belongsTo(Plant::class);
    }

    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * This user's notifications, typed as the application's Notification model
     * rather than the framework's base class.
     */
    public function appNotifications(): MorphMany
    {
        return $this->morphMany(Notification::class, 'notifiable')->latestFirst();
    }

    public function createdPurchaseOrders(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class, 'created_by');
    }

    public function approvedPurchaseOrders(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class, 'approved_by');
    }
}
